# Generated by Django 5.0.2 on 2024-04-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
